{
 "title": "zlmediakit-new",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "zlmediakit_exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stream Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "zlm_stream_info{} * on(vhost, app, stream, schema) group_left\n(\n  zlm_stream_readers{} * on(vhost, app, stream, schema) group_left\n  (\n    zlm_stream_alive_seconds{} * on(vhost, app, stream, schema) group_left\n    zlm_stream_create_time_seconds{}\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Push",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "count(zlm_stream_info{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stream Throughput (B/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "zlm_stream_bytes_per_second", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sum(zlm_sessions)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "zlm_network_threads", "legendFormat": "__auto" },
    { "expr": "zlm_work_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Networkthread Load(avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg(avg_over_time(zlm_network_thread_load_percent[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workthread Load(avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg(avg_over_time(zlm_work_thread_load_percent[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MediaSource",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zlm_statistics_media_source", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "BufferLikeString",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zlm_statistics_buffer_like_string",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BufferRaw",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zlm_statistics_buffer_raw", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Frame",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zlm_statistics_frame", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RtpPacket",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zlm_statistics_rtp_packet", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Buffer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zlm_statistics_buffer", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MultiMediaSourceMuxer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zlm_statistics_multi_media_source_muxer",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Socket",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zlm_statistics_socket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FrameImp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zlm_statistics_frame_imp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RtmpPacket",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zlm_statistics_rtmp_packet", "legendFormat": "__auto" }
   ]
  }
 ]
}